
[functions.razorpay-create-order]
enabled = true
verify_jwt = true
import_map = "./functions/razorpay-create-order/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/razorpay-create-order/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/razorpay-create-order/*.html" ]

[functions.razorpay-verify-payment]
enabled = true
verify_jwt = true
import_map = "./functions/razorpay-verify-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/razorpay-verify-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/razorpay-verify-payment/*.html" ]
